# Generated by Django 4.2.7 on 2023-12-18 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='textforpage',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
