# Generated by Django 4.2.7 on 2023-12-18 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_textforpage_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='textforpage',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AddField(
            model_name='imageforpage',
            name='image_type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='pages.imagetype'),
        ),
    ]
