# Generated by Django 4.2.7 on 2023-12-18 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_imagetype_alter_textforpage_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageforpage',
            name='image_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.imagetype'),
        ),
    ]
