# Generated by Django 4.2.7 on 2023-12-19 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_imageforpage_image_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subtext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('text', models.TextField()),
                ('for_text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.textforpage')),
            ],
        ),
    ]
