# Generated by Django 4.2.7 on 2024-01-18 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_imagetotext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagetotext',
            name='image',
            field=models.FileField(upload_to='pages_images'),
        ),
    ]
