# Generated by Django 4.2.7 on 2024-01-22 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_time_create_order_time_update_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='time_create',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
