# Generated by Django 4.2.7 on 2024-01-30 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_time_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttoorders',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
