# Generated by Django 4.1.10 on 2024-03-12 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_remove_sizetoproduct_initially'),
        ('orders', '0006_alter_producttoorders_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttoorders',
            name='size',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='products.sizetoproduct'),
            preserve_default=False,
        ),
    ]
