# Generated by Django 4.2.7 on 2023-11-17 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='fixedPrice',
        ),
        migrations.RemoveField(
            model_name='product',
            name='priceBasedOnSize',
        ),
    ]
