# Generated by Django 4.2.7 on 2023-11-20 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_fixedprice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='typebacklight',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
