# Generated by Django 4.2.7 on 2023-11-20 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_typebacklight_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='typebacklight',
            name='quantityBloks',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
