# Generated by Django 4.2.7 on 2023-11-21 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_typebacklight_quantitybloks'),
    ]

    operations = [
        migrations.AddField(
            model_name='framematerial',
            name='basis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.basis'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='framematerial',
            name='fix_price',
            field=models.FloatField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='framematerial',
            name='price_of_consumables',
            field=models.DecimalField(decimal_places=5, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='framematerial',
            name='size_price',
            field=models.FloatField(),
            preserve_default=False,
        ),
    ]
