# Generated by Django 4.2.7 on 2023-11-21 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_framematerial_basis_framematerial_fix_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='framematerial',
            name='fix_price',
        ),
    ]
