# Generated by Django 4.2.7 on 2023-11-21 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_framematerial_fix_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='framematerial',
            name='fixe_price',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
