# Generated by Django 4.2.7 on 2023-11-21 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_framematerial_fixe_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='framematerial',
            old_name='fixe_price',
            new_name='fixed_price',
        ),
    ]
