# Generated by Django 4.2.7 on 2023-11-24 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_rename_fixe_price_framematerial_fixed_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pesostruy',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
