# Generated by Django 4.2.7 on 2023-11-24 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_pesostruy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='framematerial',
            name='fixed_price',
        ),
        migrations.AddField(
            model_name='framematerial',
            name='material_price',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='framematerial',
            name='price_work_less',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='framematerial',
            name='price_work_more',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
