# Generated by Django 4.2.7 on 2023-11-24 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_rename_price_of_consumables_framematerial_consumables_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='framematerial',
            name='with_dye',
            field=models.BooleanField(),
            preserve_default=False,
        ),
    ]
