# Generated by Django 4.2.7 on 2023-11-25 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_framematerial_with_dye'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlywoodBasis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('price', models.DecimalField(decimal_places=5, max_digits=10)),
                ('plywood_length', models.FloatField()),
                ('plywood_width', models.FloatField()),
                ('cutting', models.DecimalField(decimal_places=5, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='PlywoodBasisToProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.plywoodbasis')),
            ],
        ),
        migrations.RemoveField(
            model_name='framematerial',
            name='basis',
        ),
        migrations.RemoveField(
            model_name='product',
            name='basis',
        ),
        migrations.DeleteModel(
            name='Basis',
        ),
        migrations.AddField(
            model_name='plywoodbasistoproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
