# Generated by Django 4.2.7 on 2023-12-08 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_alter_product_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='backlighttoproduct',
            old_name='typeBackLight',
            new_name='quantityBlocks',
        ),
        migrations.RenameField(
            model_name='typebacklight',
            old_name='quantityBloks',
            new_name='quantityBlocks',
        ),
    ]
