# Generated by Django 4.2.7 on 2023-12-08 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_rename_typebacklight_backlighttoproduct_quantityblocks_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='backlighttoproduct',
            old_name='quantityBlocks',
            new_name='typeBackLight',
        ),
    ]
