# Generated by Django 4.1.10 on 2024-02-12 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_product_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='typebacklight',
            name='name_for_admin',
            field=models.CharField(default='', max_length=128, unique=True),
            preserve_default=False,
        ),
    ]
