# Generated by Django 4.1.10 on 2024-02-25 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_typebacklight_name_for_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sizetoproduct',
            name='initially',
        ),
    ]
